#!/usr/bin/env python3
# coding: utf-8

import subprocess

from .base_test import BaseTest
from testgres.exceptions import QueryException


class DDLTest(BaseTest):

	def test_first_null_field_in_recovery(self):

		node = self.node
		node.start()

		node.safe_psql("""
			CREATE EXTENSION IF NOT EXISTS orioledb;

			CREATE TABLE o_test_1(
				val_1 int,
				val_2 int PRIMARY KEY
			)USING orioledb;

			INSERT INTO o_test_1(val_1, val_2) VALUES (1, 10);

			INSERT INTO o_test_1 (val_2) VALUES (5);
		""")

		self.assertEqual([(None, 5), (1, 10)], node.execute("TABLE o_test_1"))
		node.stop(['-m', 'immediate'])

		node.start()
		self.assertEqual([(None, 5), (1, 10)], node.execute("TABLE o_test_1"))
		node.stop()

	def test_update_default_to_null_same_trx(self):
		with self.node as node:
			node.start()
			node.safe_psql("CREATE EXTENSION orioledb;")
			with node.connect() as con:
				con.execute("CREATE TABLE o_test () USING orioledb;")
				con.execute("INSERT INTO o_test DEFAULT VALUES;")
				con.execute("""
					ALTER TABLE o_test ADD COLUMN val_1 int DEFAULT 1;
				""")
				con.execute("""
					CREATE INDEX ON o_test (val_1);
				""")
				self.assertEqual([(1, )],
				                 con.execute("""
									 SET LOCAL enable_seqscan = false;
									 SELECT * FROM o_test;
								 """))
				con.execute("""
					UPDATE o_test SET val_1 = NULL;
				""")
				con.execute("""
					SELECT * FROM o_test WHERE val_1 IS NULL;
				""")
				self.assertEqual([(None, )],
				                 con.execute("""
									 SELECT * FROM o_test WHERE val_1 IS NULL;
								 """))
			node.stop()

	def test_alter_table_phase2_metadata(self):
		with self.node as node:
			node.start()
			node.safe_psql("""
				CREATE EXTENSION orioledb;
				CREATE DOMAIN positive_int AS int CHECK (VALUE > 0);
				CREATE TABLE o_alter (id int, payload text) USING orioledb;
				INSERT INTO o_alter VALUES (1, 'one'), (2, 'two');

				ALTER TABLE o_alter
					ADD COLUMN constant_col int DEFAULT 7,
					ADD COLUMN nullable_col int,
					ADD COLUMN domain_col positive_int DEFAULT 3,
					ADD COLUMN generated_col int GENERATED ALWAYS AS
						(id + constant_col) STORED,
					ADD UNIQUE (constant_col, id);
				ALTER TABLE o_alter ADD COLUMN IF NOT EXISTS constant_col int;
				ALTER TABLE o_alter
					ADD COLUMN identity_col bigint GENERATED BY DEFAULT AS IDENTITY;
				ALTER TABLE o_alter ALTER COLUMN payload SET DEFAULT 'new';
				ALTER TABLE o_alter ALTER COLUMN payload SET NOT NULL;
				ALTER TABLE o_alter ALTER COLUMN payload SET STORAGE EXTERNAL;
				ALTER TABLE o_alter DROP COLUMN nullable_col,
					DROP COLUMN IF EXISTS nullable_col,
					ADD COLUMN nullable_col text DEFAULT 'again';

				CREATE UNIQUE INDEX o_alter_id_idx ON o_alter (id);
				ALTER TABLE o_alter ADD PRIMARY KEY USING INDEX o_alter_id_idx;
				ALTER TABLE o_alter SET (fillfactor = 70);

				CREATE TABLE o_type (id int PRIMARY KEY, value varchar(20))
					USING orioledb;
				CREATE INDEX o_type_value_idx ON o_type (value);
				INSERT INTO o_type VALUES (1, 'one');
				ALTER TABLE o_type ALTER COLUMN value TYPE text;

				CREATE TABLE o_pkey_collation (
					key text COLLATE "C" PRIMARY KEY,
					group_id int,
					payload text
				) USING orioledb;
				CREATE INDEX o_pkey_collation_group_idx
					ON o_pkey_collation (group_id);
				INSERT INTO o_pkey_collation
					SELECT i::text, i % 3, 'value-' || i
					FROM generate_series(1, 30) i;
				ALTER TABLE o_pkey_collation ALTER COLUMN key
					TYPE text COLLATE "POSIX";

				CREATE TABLE o_phase2_combined (
					key text COLLATE "C" PRIMARY KEY,
					value text COLLATE "C"
				) USING orioledb;
				CREATE INDEX o_phase2_combined_value_idx
					ON o_phase2_combined (value);
				INSERT INTO o_phase2_combined
					SELECT i::text, (100 - i)::text
					FROM generate_series(1, 100) i;
				ALTER TABLE o_phase2_combined
					ALTER COLUMN key TYPE text COLLATE "POSIX",
					ALTER COLUMN value TYPE text COLLATE "POSIX";

				CREATE TABLE o_phase2_part (
					key text COLLATE "C",
					part int,
					value int,
					PRIMARY KEY (key, part)
				) PARTITION BY RANGE (part);
				CREATE TABLE o_phase2_part_1
					PARTITION OF o_phase2_part
					FOR VALUES FROM (0) TO (50) USING orioledb;
				CREATE TABLE o_phase2_part_2
					PARTITION OF o_phase2_part
					FOR VALUES FROM (50) TO (101) USING orioledb;
				CREATE INDEX o_phase2_part_value_idx
					ON o_phase2_part (value);
				INSERT INTO o_phase2_part
					SELECT i::text, i, i FROM generate_series(1, 100) i;
				ALTER TABLE o_phase2_part ALTER COLUMN key
					TYPE text COLLATE "POSIX";

				CREATE TABLE o_parent (id int PRIMARY KEY) USING orioledb;
				CREATE TABLE o_child () INHERITS (o_parent) USING orioledb;
				INSERT INTO o_parent VALUES (1);
				INSERT INTO o_child VALUES (2);
				ALTER TABLE o_parent ADD COLUMN inherited_col int DEFAULT 11;
			""")
			self.assertEqual([(1, 'one', 7, 3, 8, 1, 'again'),
			                  (2, 'two', 7, 3, 9, 2, 'again')],
			                 node.execute("SELECT * FROM o_alter ORDER BY id"))
			self.assertEqual([(1, 11), (2, 11)],
			                 node.execute("""
					SELECT id, inherited_col FROM o_parent ORDER BY id
				"""))
			node.stop(['-m', 'immediate'])
			node.start()
			self.assertEqual([(1, 'one')], node.execute("""
				SET enable_seqscan = false;
				SELECT * FROM o_type WHERE value = 'one';
			"""))
			self.assertEqual([(3, ), (6, ), (9, ), (12, ), (15, ), (18, ),
			                  (21, ), (24, ), (27, ), (30, )], node.execute("""
				SET enable_seqscan = false;
				SELECT key::int FROM o_pkey_collation
				WHERE group_id = 0 ORDER BY key::int;
			"""))
			self.assertTrue(node.execute("""
				SELECT orioledb_tbl_check('o_pkey_collation'::regclass);
			""")[0][0])
			self.assertEqual([(100, )], node.execute("""
				SET enable_seqscan = false;
				SELECT count(*) FROM o_phase2_combined WHERE value >= '0';
			"""))
			self.assertTrue(node.execute("""
				SELECT orioledb_tbl_check('o_phase2_combined'::regclass);
			""")[0][0])
			self.assertEqual([(100, )], node.execute("""
				SET enable_seqscan = false;
				SELECT count(*) FROM o_phase2_part
				WHERE value BETWEEN 1 AND 100;
			"""))
			self.assertEqual([(True, True)], node.execute("""
				SELECT orioledb_tbl_check('o_phase2_part_1'::regclass),
					orioledb_tbl_check('o_phase2_part_2'::regclass);
			"""))
			self.assertEqual([(3, 'new', 7, 3, 10, 'again', True)],
			                 node.execute("""
					INSERT INTO o_alter (id) VALUES (3)
					RETURNING id, payload, constant_col, domain_col,
						generated_col, nullable_col, identity_col IS NOT NULL
				"""))
			node.stop()

	def test_cached_custom_path(self):
		with self.node as node:
			node.append_conf(filename='postgresql.conf',
			                 default_table_access_method='orioledb')
			node.start()

			node.safe_psql("""CREATE EXTENSION orioledb;""")
			pgbench = node.pgbench(options=["-i", "-s", "1"],
			                       stdout=subprocess.DEVNULL,
			                       stderr=subprocess.DEVNULL)
			self.assertEqual(pgbench.wait(), 0)
			node.stop()
			node.start()
			with node.connect() as con:
				con.execute("""
					PREPARE P0_5 AS UPDATE pgbench_accounts
						SET abalance = abalance + $1 WHERE aid = $2;
				""")
				con.commit()
				con.execute("EXECUTE P0_5('2763', '76750');")
				con.execute("EXECUTE P0_5('-3338', '97628');")
				con.execute("EXECUTE P0_5('-3064', '59049');")
				con.execute("EXECUTE P0_5('586', '12143');")
				con.execute("EXECUTE P0_5('-1653', '13061');")
				con.execute("EXECUTE P0_5('-2841', '93929');")
				con.commit()
				con.execute("EXECUTE P0_5('3165', '17463');")

	def test_sys_attrs(self):
		node = self.node
		node.start()

		node.safe_psql("""
			CREATE EXTENSION IF NOT EXISTS orioledb;
			CREATE TABLE o_test_1 (val_1 int)USING orioledb;
			INSERT INTO o_test_1 VALUES (1);
		""")
		tableoid = node.execute("SELECT 'o_test_1'::regclass::oid;")[0][0]
		self.assertEqual(
		    node.execute("SELECT ctid, * FROM o_test_1;")[0], ('(0,1)', 1))
		self.assertEqual(
		    node.execute("SELECT tableoid, * FROM o_test_1;")[0],
		    (tableoid, 1))
		error_fields = ["xmin", "xmax", "cmin", "cmax"]
		for field in error_fields:
			with self.assertRaises(QueryException) as e:
				node.safe_psql(f"SELECT {field}, * FROM o_test_1;")
			self.assertErrorMessageEquals(e, (f"orioledb tuples does not have "
			                                  f"system attribute: {field}"))

	def test_non_trx_recreate_expr_index(self):

		node = self.node
		node.start()

		con1 = node.connect()

		con1.begin()

		con1.execute("""
			CREATE EXTENSION IF NOT EXISTS orioledb;

			CREATE TABLE o_test_1 (
				val_1 int
			) USING orioledb;

			CREATE INDEX ind_1 ON o_test_1 ((val_1::text COLLATE "C"));

			ALTER INDEX ind_1 ALTER COLUMN 1 SET STATISTICS 100;
		""")

		con1.commit()

		con1.begin()
		con1.commit()

	def test_non_trx_recreate_partial_index(self):

		node = self.node
		node.start()

		con1 = node.connect()

		con1.begin()

		con1.execute("""

			CREATE EXTENSION IF NOT EXISTS orioledb;

			CREATE TABLE o_test_1 (
				val_1 int
			) USING orioledb;

			CREATE INDEX ind_1 ON o_test_1 (val_1) WHERE (val_1::text > 'a');

			ALTER INDEX ind_1 SET (fillfactor=40);
		""")

		con1.commit()

		con1.begin()
		con1.commit()

	def test_shared_root_info_not_using_undo(self):
		node = self.node
		node.start()
		node.safe_psql("""
			CREATE EXTENSION IF NOT EXISTS orioledb;

			CREATE TABLE test (
				id integer
			) USING orioledb;
		""")

		con1 = node.connect()

		con1.begin()

		con1.execute("""
			INSERT INTO test(id) VALUES (1);
		""")

		relfilenode = con1.execute("""
			SELECT relfilenode from pg_class WHERE oid = 'test'::regclass::oid;
		""")[0][0]

		self.assertEqual(
		    con1.execute(f"""
			SELECT r->'tupHdr'->'deleted'
				FROM orioledb_sys_tree_rows(1) r
					WHERE (r->'key'->'relnode')::int = {relfilenode};
		""")[0][0], False)

		con1.execute("""
			DROP TABLE test;
		""")

		self.assertEqual(
		    con1.execute(f"""
			SELECT r->'tupHdr'->'deleted'
				FROM orioledb_sys_tree_rows(1) r
					WHERE (r->'key'->'relnode')::int = {relfilenode};
		""")[0][0], False)

		con1.commit()

		self.assertEqual(
		    con1.execute(f"""
			SELECT COUNT(*) FROM orioledb_sys_tree_rows(1) r;
		""")[0][0], 0)

	def test_drop_index_concurrently_statement_timeout(self):
		"""
		DROP INDEX CONCURRENTLY keeps only ShareUpdateExclusiveLock, so
		during commit stage interrupts are switched off, so statement_timeout
		was never processed and the backend waited for the reader instead of
		failing.
		"""
		node = self.node
		node.start()
		node.safe_psql("""
			CREATE EXTENSION IF NOT EXISTS orioledb;

			CREATE TABLE o_test_drop_index (
				val_1 int PRIMARY KEY,
				val_2 int
			) USING orioledb;

			INSERT INTO o_test_drop_index
				SELECT v, v FROM generate_series(1, 100) v;

			CREATE INDEX o_test_drop_index_ix ON o_test_drop_index (val_2);
		""")

		reader = node.connect()
		dropper = node.connect(autocommit=True)
		try:
			reader.execute("SET idle_in_transaction_session_timeout = '30s';")
			reader.execute("SELECT * FROM o_test_drop_index LIMIT 1;")

			# Here we should catch an error by timeout, because the transaction
			# holds locks.
			dropper.execute("SET statement_timeout = '1s';")
			with self.assertRaises(Exception) as e:
				dropper.execute("""
					DROP INDEX CONCURRENTLY o_test_drop_index_ix;
				""")
			self.assertIn("canceling statement due to statement timeout",
			              str(e.exception))

			# The timed-out drop left the index in place but, as in upstream
			# PG, invalid: index_drop() commits indisvalid = false before
			# WaitForLockers() blocks, so the cancel does not roll it back.
			self.assertEqual([(False, )],
			                 dropper.execute("""
								 SELECT indisvalid FROM pg_index
									 WHERE indexrelid =
										   'o_test_drop_index_ix'::regclass;
							 """))

			# Nobody reads the table anymore, so the drop goes through.
			reader.rollback()
			dropper.execute("""
				DROP INDEX CONCURRENTLY o_test_drop_index_ix;
			""")
			self.assertEqual([(0, )],
			                 dropper.execute("""
								 SELECT count(*) FROM pg_class
									 WHERE relname = 'o_test_drop_index_ix';
							 """))
		finally:
			reader.close()
			dropper.close()

		node.stop()
