CREATE SCHEMA generated_test;
SET SESSION search_path = 'generated_test';
CREATE EXTENSION orioledb;

SELECT split_part(setting, '.', 1) major_version
	FROM pg_settings WHERE name = 'server_version';

CREATE TABLE o_test_generated (
	a int,
	b int GENERATED ALWAYS AS (a * 2) STORED
) USING orioledb;

INSERT INTO o_test_generated VALUES (1), (2);
SELECT * FROM o_test_generated;

CREATE TABLE o_test_generated_like (
	LIKE o_test_generated INCLUDING GENERATED
) USING orioledb;

INSERT INTO o_test_generated_like VALUES (5), (6);
SELECT * FROM o_test_generated_like;

CREATE TABLE o_test_drop_expression (
    a int,
	b int GENERATED ALWAYS AS (a * 2) STORED
) USING orioledb;

INSERT INTO o_test_drop_expression VALUES (1);
INSERT INTO o_test_drop_expression VALUES (2);
SELECT * FROM o_test_drop_expression;

ALTER TABLE o_test_drop_expression ALTER COLUMN a DROP EXPRESSION;
ALTER TABLE o_test_drop_expression ALTER COLUMN b DROP EXPRESSION;

INSERT INTO o_test_drop_expression VALUES (3);
SELECT * FROM o_test_drop_expression;

CREATE TABLE o_test_drop_expression_next (
    a int,
    b int GENERATED ALWAYS AS (a * 2) STORED
) USING orioledb;
ALTER TABLE o_test_drop_expression_next ALTER COLUMN b DROP EXPRESSION;
DROP TABLE o_test_drop_expression_next;

CREATE TABLE o_test_add_identity_exist (
    a SMALLINT GENERATED BY DEFAULT AS IDENTITY (START WITH 7 INCREMENT BY 5),
    b TEXT
) USING orioledb;

ALTER TABLE o_test_add_identity_exist
	ALTER COLUMN a ADD GENERATED ALWAYS AS IDENTITY;
INSERT INTO o_test_add_identity_exist (b) VALUES ('a'), ('b'), ('c');
SELECT * FROM o_test_add_identity_exist;

CREATE TABLE o_test_add_identity (
    a SMALLINT,
    b TEXT
) USING orioledb;
ALTER TABLE o_test_add_identity
	ALTER COLUMN a SET NOT NULL,
	ALTER COLUMN a ADD GENERATED ALWAYS AS IDENTITY;
INSERT INTO o_test_add_identity (b) VALUES ('a'), ('b'), ('c');
SELECT * FROM o_test_add_identity;

ALTER TABLE o_test_add_identity
	ALTER COLUMN a RESTART WITH 10;
INSERT INTO o_test_add_identity (b) VALUES ('A'), ('B'), ('C');
SELECT * FROM o_test_add_identity;

ALTER TABLE o_test_add_identity
	ALTER COLUMN a DROP IDENTITY,
	ALTER COLUMN a DROP NOT NULL;
INSERT INTO o_test_add_identity (b) VALUES ('X'), ('Y'), ('Z');
SELECT * FROM o_test_add_identity;

CREATE TABLE o_test_generated_null (
    val_1 text,
    val_2 int GENERATED ALWAYS AS (1 + COALESCE(val_3::text, '0')::int) STORED,
	val_3 int DEFAULT 5
) USING orioledb;
\d+ o_test_generated_null
INSERT INTO o_test_generated_null (val_1, val_3) VALUES (1, NULL);
INSERT INTO o_test_generated_null (val_1, val_3) VALUES (NULL, NULL);
SELECT orioledb_tbl_structure('o_test_generated_null'::regclass, 'nue');
SELECT * FROM o_test_generated_null;

CREATE TABLE o_test_tableoid (
  val_1 int PRIMARY KEY,
  val_2 bool GENERATED ALWAYS
    AS (tableoid = 'o_test_tableoid'::regclass) STORED
) USING orioledb;

INSERT INTO o_test_tableoid VALUES (1), (2);

ALTER TABLE o_test_tableoid ADD COLUMN
  val_3 regclass GENERATED ALWAYS AS (tableoid) STORED;

SELECT * FROM o_test_tableoid;

CREATE TABLE o_test_generated_alter_type (
    val_1 int,
    val_3 int GENERATED ALWAYS AS (val_1 * 2) STORED
) USING orioledb;

INSERT INTO o_test_generated_alter_type (val_1) VALUES (1), (3);
SELECT * FROM o_test_generated_alter_type;
SELECT orioledb_tbl_structure('o_test_generated_alter_type'::regclass, 'nue');

ALTER TABLE o_test_generated_alter_type ALTER COLUMN val_3 TYPE numeric;
SELECT * FROM o_test_generated_alter_type;

-- Test AT_SetExpression (ALTER TABLE ... ALTER COLUMN ... SET EXPRESSION)
-- Two generated columns altered in a single ALTER TABLE statement
CREATE TABLE o_test_set_expression (
	i int PRIMARY KEY,
	price numeric(10,2),
	quantity int,
	total numeric(10,2) GENERATED ALWAYS AS (price * quantity) STORED,
	discounted numeric(10,2) GENERATED ALWAYS AS (price * 0.9) STORED
) USING orioledb;

INSERT INTO o_test_set_expression (i, price, quantity) VALUES (1, 10.50, 5);
INSERT INTO o_test_set_expression (i, price, quantity) VALUES (2, 25.00, 3);
INSERT INTO o_test_set_expression (i, price, quantity) VALUES (3, 7.99, 10);

-- Verify initial generated column values
SELECT i, price, quantity, total, discounted FROM o_test_set_expression ORDER BY i;

-- Snapshot the table before changing the expressions
CREATE MATERIALIZED VIEW o_test_set_expr_mv USING orioledb AS
	SELECT * FROM o_test_set_expression ORDER BY i;

SELECT * FROM o_test_set_expr_mv ORDER BY i;

-- Check the initial generated column expressions in catalog
SELECT a.attname, pg_get_expr(d.adbin, d.adrelid) as generation_expr
FROM pg_attribute a
JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
WHERE a.attrelid = 'o_test_set_expression'::regclass
  AND a.attname IN ('total', 'discounted')
ORDER BY a.attnum;

-- Change both generated columns in a single ALTER TABLE
ALTER TABLE o_test_set_expression
  ALTER COLUMN total SET EXPRESSION AS (price * quantity * 1.1),
  ALTER COLUMN discounted SET EXPRESSION AS (price * 0.75);

-- Verify both expressions were updated in catalog
SELECT a.attname, pg_get_expr(d.adbin, d.adrelid) as generation_expr
FROM pg_attribute a
JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
WHERE a.attrelid = 'o_test_set_expression'::regclass
  AND a.attname IN ('total', 'discounted')
ORDER BY a.attnum;

-- Verify all existing values were recalculated with new expressions
SELECT i, price, quantity, total, discounted,
	(price * quantity * 1.1) as expected_total,
	(price * 0.75) as expected_discounted
FROM o_test_set_expression ORDER BY i;

-- Matview should still have the old snapshot
SELECT * FROM o_test_set_expr_mv ORDER BY i;

-- Refresh picks up the new expressions
REFRESH MATERIALIZED VIEW o_test_set_expr_mv;
SELECT * FROM o_test_set_expr_mv ORDER BY i;

-- Update and verify recalculation
UPDATE o_test_set_expression SET price = 15.00 WHERE i = 1;

SELECT i, price, quantity, total, discounted,
	(price * quantity * 1.1) as expected_total,
	(price * 0.75) as expected_discounted
FROM o_test_set_expression ORDER BY i;

-- Insert new row to verify new expressions are used for new data
INSERT INTO o_test_set_expression (i, price, quantity) VALUES (4, 20.00, 2);

SELECT i, price, quantity, total, discounted,
	(price * quantity * 1.1) as expected_total,
	(price * 0.75) as expected_discounted
FROM o_test_set_expression ORDER BY i;

DROP TABLE o_test_set_expression CASCADE;

-- Virtual generated columns (PG18+).  Three regressions we hit on
-- orioledb tables during ALTER TABLE rewrites:
--   * CHECK constraint referencing a VIRTUAL gen col raised
--     "unexpected virtual generated column reference" during ADD COLUMN
--     ... DEFAULT ... CHECK (gen_col_expr) because the expression
--     wasn't expanded before ExecCheck.
--   * ALTER COLUMN ... TYPE ... USING <virtual_col_ref> raised the same
--     error because the USING expression was likewise unexpanded.
--   * A multi-action ALTER TABLE that dropped a VIRTUAL column in the
--     same statement as ALTER COLUMN TYPE raised
--     "cache lookup failed for type 0" because the rewrite loop touched
--     the dropped attribute's type.
SELECT current_setting('server_version_num')::int >= 180000 AS pg18 \gset
\if :pg18

-- CHECK referencing a virtual column survives an ADD COLUMN rewrite.
CREATE TABLE o_test_virt_check (
	a int PRIMARY KEY,
	b int GENERATED ALWAYS AS (a * 2) VIRTUAL
) USING orioledb;
INSERT INTO o_test_virt_check (a) VALUES (10), (30);
-- Adding a CHECK that holds for every row alongside a defaulted new
-- column triggers the table rewrite without erroring.
ALTER TABLE o_test_virt_check
	ADD COLUMN c float8 DEFAULT 0 CHECK (b < 100);
SELECT * FROM o_test_virt_check ORDER BY a;
-- Same shape but the CHECK is violated by an existing row -- must raise
-- the upstream check-constraint error, not the bare virtual reference.
INSERT INTO o_test_virt_check (a) VALUES (50);
ALTER TABLE o_test_virt_check
	ADD COLUMN d float8 DEFAULT 0 CHECK (b < 50);

-- USING expression that reads a virtual column.
CREATE TABLE o_test_virt_using (
	a int PRIMARY KEY,
	b int GENERATED ALWAYS AS (a * 2) VIRTUAL,
	e int
) USING orioledb;
INSERT INTO o_test_virt_using VALUES (1), (2);
ALTER TABLE o_test_virt_using ALTER COLUMN e TYPE bigint USING b;
SELECT * FROM o_test_virt_using ORDER BY a;

-- Multi-action ALTER that drops a VIRTUAL column alongside an
-- ALTER COLUMN ... TYPE rewrite.
CREATE TABLE o_test_virt_drop (
	a int, b int,
	x int GENERATED ALWAYS AS ((a + b) * 2) VIRTUAL
) USING orioledb;
INSERT INTO o_test_virt_drop (a, b) VALUES (3, 7), (4, 11);
ALTER TABLE o_test_virt_drop
	DROP COLUMN x,
	ALTER COLUMN a TYPE bigint,
	ALTER COLUMN b TYPE bigint,
	ADD COLUMN x bigint GENERATED ALWAYS AS ((a + b) * 2) VIRTUAL;
\d o_test_virt_drop
SELECT * FROM o_test_virt_drop ORDER BY a;

-- Same shape but for a STORED generated column whose type was first
-- altered to a varlena (numeric attlen=-1).  The dropped placeholder
-- inherits attlen=-1, and the rewrite loop's "skip generated" branch
-- used to fire before the dropped-skip, leaving tts_isnull[i] = false
-- and tts_values[i] = 0; tts_orioledb_toast would then crash on
-- VARATT_IS_EXTERNAL_ONDISK(NULL).
CREATE TABLE o_test_stored_drop (
	a int, b int,
	x int GENERATED ALWAYS AS ((a + b) * 2) STORED
) USING orioledb;
INSERT INTO o_test_stored_drop (a, b) VALUES (3, 7), (4, 11);
ALTER TABLE o_test_stored_drop ALTER COLUMN x TYPE numeric;
INSERT INTO o_test_stored_drop (a, b) VALUES (NULL, NULL);
ALTER TABLE o_test_stored_drop
	DROP COLUMN x,
	ALTER COLUMN a TYPE bigint,
	ALTER COLUMN b TYPE bigint,
	ADD COLUMN x bigint GENERATED ALWAYS AS ((a + b) * 2) STORED;
\d o_test_stored_drop
SELECT * FROM o_test_stored_drop ORDER BY a NULLS LAST;

\endif

DROP EXTENSION orioledb CASCADE;
DROP SCHEMA generated_test CASCADE;
RESET search_path;
