CREATE SCHEMA generated_test;
SET SESSION search_path = 'generated_test';
CREATE EXTENSION orioledb;

CREATE TABLE o_test_generated (
	a int,
	b int GENERATED ALWAYS AS (a * 2) STORED
) USING orioledb;

INSERT INTO o_test_generated VALUES (1), (2);
SELECT * FROM o_test_generated;

CREATE TABLE o_test_generated_like (
	LIKE o_test_generated INCLUDING GENERATED
) USING orioledb;

INSERT INTO o_test_generated_like VALUES (5), (6);
SELECT * FROM o_test_generated_like;

CREATE TABLE o_test_drop_expression (
    a int,
	b int GENERATED ALWAYS AS (a * 2) STORED
) USING orioledb;

INSERT INTO o_test_drop_expression VALUES (1);
INSERT INTO o_test_drop_expression VALUES (2);
SELECT * FROM o_test_drop_expression;

ALTER TABLE o_test_drop_expression ALTER COLUMN a DROP EXPRESSION;
ALTER TABLE o_test_drop_expression ALTER COLUMN b DROP EXPRESSION;

INSERT INTO o_test_drop_expression VALUES (3);
SELECT * FROM o_test_drop_expression;


CREATE TABLE o_test_add_identity_exist (
    a SMALLINT GENERATED BY DEFAULT AS IDENTITY (START WITH 7 INCREMENT BY 5),
    b TEXT
) USING orioledb;

ALTER TABLE o_test_add_identity_exist
	ALTER COLUMN a ADD GENERATED ALWAYS AS IDENTITY;
INSERT INTO o_test_add_identity_exist (b) VALUES ('a'), ('b'), ('c');
SELECT * FROM o_test_add_identity_exist;

CREATE TABLE o_test_add_identity (
    a SMALLINT,
    b TEXT
) USING orioledb;
ALTER TABLE o_test_add_identity
	ALTER COLUMN a SET NOT NULL,
	ALTER COLUMN a ADD GENERATED ALWAYS AS IDENTITY;
INSERT INTO o_test_add_identity (b) VALUES ('a'), ('b'), ('c');
SELECT * FROM o_test_add_identity;

ALTER TABLE o_test_add_identity
	ALTER COLUMN a RESTART WITH 10;
INSERT INTO o_test_add_identity (b) VALUES ('A'), ('B'), ('C');
SELECT * FROM o_test_add_identity;

ALTER TABLE o_test_add_identity
	ALTER COLUMN a DROP IDENTITY,
	ALTER COLUMN a DROP NOT NULL;
INSERT INTO o_test_add_identity (b) VALUES ('X'), ('Y'), ('Z');
SELECT * FROM o_test_add_identity;

CREATE TABLE o_test_generated_null (
    val_1 text,
    val_2 int GENERATED ALWAYS AS (1 + COALESCE(val_3::text, '0')::int) STORED,
	val_3 int DEFAULT 5
) USING orioledb;
\d+ o_test_generated_null
INSERT INTO o_test_generated_null (val_1, val_3) VALUES (1, NULL);
INSERT INTO o_test_generated_null (val_1, val_3) VALUES (NULL, NULL);
SELECT orioledb_tbl_structure('o_test_generated_null'::regclass, 'nue');
SELECT * FROM o_test_generated_null;

CREATE TABLE o_test_tableoid (
  val_1 int PRIMARY KEY,
  val_2 bool GENERATED ALWAYS
    AS (tableoid = 'o_test_tableoid'::regclass) STORED
) USING orioledb;

INSERT INTO o_test_tableoid VALUES (1), (2);

ALTER TABLE o_test_tableoid ADD COLUMN
  val_3 regclass GENERATED ALWAYS AS (tableoid) STORED;

SELECT * FROM o_test_tableoid;

CREATE TABLE o_test_generated_alter_type (
    val_1 int,
    val_3 int GENERATED ALWAYS AS (val_1 * 2) STORED
) USING orioledb;

INSERT INTO o_test_generated_alter_type (val_1) VALUES (1), (3);
SELECT * FROM o_test_generated_alter_type;
SELECT orioledb_tbl_structure('o_test_generated_alter_type'::regclass, 'nue');

ALTER TABLE o_test_generated_alter_type ALTER COLUMN val_3 TYPE numeric;
SELECT * FROM o_test_generated_alter_type;

-- Test AT_SetExpression (ALTER TABLE ... ALTER COLUMN ... SET EXPRESSION)
-- AT_SetExpression allows changing the generation expression for a STORED generated column
-- This feature is available in PostgreSQL 17+
CREATE TABLE o_test_set_expression (
	i int PRIMARY KEY,
	price numeric(10,2),
	quantity int,
	total numeric(10,2) GENERATED ALWAYS AS (price * quantity) STORED
) USING orioledb;

-- Insert test data
INSERT INTO o_test_set_expression (i, price, quantity) VALUES (1, 10.50, 5);
INSERT INTO o_test_set_expression (i, price, quantity) VALUES (2, 25.00, 3);
INSERT INTO o_test_set_expression (i, price, quantity) VALUES (3, 7.99, 10);

-- Verify initial generated column values (price * quantity)
SELECT i, price, quantity, total FROM o_test_set_expression ORDER BY i;

-- Check the initial generated column expression in catalog
SELECT a.attname, a.attgenerated, pg_get_expr(d.adbin, d.adrelid) as generation_expr
FROM pg_attribute a
JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
WHERE a.attrelid = 'o_test_set_expression'::regclass
  AND a.attname = 'total';

-- Use AT_SetExpression to change the generation formula
-- Change from (price * quantity) to (price * quantity * 1.1) to add 10% markup
-- FIXME: Unsupported in orioledb yet. All further tests don't work yet.
ALTER TABLE o_test_set_expression
  ALTER COLUMN total SET EXPRESSION AS (price * quantity * 1.1);

-- Verify the expression was updated in catalog
SELECT a.attname, a.attgenerated, pg_get_expr(d.adbin, d.adrelid) as generation_expr
FROM pg_attribute a
JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
WHERE a.attrelid = 'o_test_set_expression'::regclass
  AND a.attname = 'total';

-- Verify all existing values were recalculated with new expression
SELECT i, price, quantity, total,
	(price * quantity * 1.1) as expected_total
FROM o_test_set_expression
ORDER BY i;

UPDATE o_test_set_expression SET price = 15.00 WHERE i = 1;

-- Verify recalculation after update
SELECT i, price, quantity, total,
	(price * quantity * 1.1) as expected_total
FROM o_test_set_expression
ORDER BY i;

-- Insert new row to verify new expression is used for new data
INSERT INTO o_test_set_expression (i, price, quantity) VALUES (4, 20.00, 2);

SELECT i, price, quantity, total,
	(price * quantity * 1.1) as expected_total
FROM o_test_set_expression
ORDER BY i;

DROP TABLE o_test_set_expression CASCADE;

DROP EXTENSION orioledb CASCADE;
DROP SCHEMA generated_test CASCADE;
RESET search_path;
