EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 ORDER BY id1;
SELECT id1, id2 FROM o_pk3 ORDER BY id1;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 ORDER BY id1 DESC;
SELECT id1, id2 FROM o_pk3 ORDER BY id1 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 ORDER BY id1, id2;
SELECT id1, id2 FROM o_pk3 ORDER BY id1, id2;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 ORDER BY id1 DESC, id2;
SELECT id1, id2 FROM o_pk3 ORDER BY id1 DESC, id2;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 ORDER BY id1, id2 DESC;
SELECT id1, id2 FROM o_pk3 ORDER BY id1, id2 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 ORDER BY id1 DESC, id2 DESC;
SELECT id1, id2 FROM o_pk3 ORDER BY id1 DESC, id2 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2;
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id2 = 'xxyyy';
SELECT id1, id2 FROM o_pk3 WHERE id2 = 'xxyyy';
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 = 'xxyyy';
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 = 'xxyyy';
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 > 'xxyyy';
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 > 'xxyyy';
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 > 'xxyyy' ORDER BY id1 DESC;
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 > 'xxyyy' ORDER BY id1 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 < 'xxyyy';
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 < 'xxyyy';
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 < 'xxyyy' ORDER BY id1 DESC;
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 < 'xxyyy' ORDER BY id1 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 >= 'xxyyy';
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 >= 'xxyyy';
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 >= 'xxyyy' ORDER BY id1 DESC;
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 >= 'xxyyy' ORDER BY id1 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 <= 'xxyyy';
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 <= 'xxyyy';
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 <= 'xxyyy' ORDER BY id1 DESC;
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 <= 'xxyyy' ORDER BY id1 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 >= 'xyy' AND id2 <= 'xxyyy';
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 >= 'xyy' AND id2 <= 'xxyyy';
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 >= 'xyy' AND id2 <= 'xxyyy' ORDER BY id1 DESC;
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 >= 'xyy' AND id2 <= 'xxyyy' ORDER BY id1 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 > 'xyy' AND id2 <= 'xxyyy';
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 > 'xyy' AND id2 <= 'xxyyy';
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 > 'xyy' AND id2 <= 'xxyyy' ORDER BY id1 DESC;
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 > 'xyy' AND id2 <= 'xxyyy' ORDER BY id1 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 >= 'xyy' AND id2 < 'xxyyy';
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 >= 'xyy' AND id2 < 'xxyyy';
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 >= 'xyy' AND id2 < 'xxyyy' ORDER BY id1 DESC;
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 >= 'xyy' AND id2 < 'xxyyy' ORDER BY id1 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 > 'xyy' AND id2 < 'xxyyy';
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 > 'xyy' AND id2 < 'xxyyy';
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 > 'xyy' AND id2 < 'xxyyy' ORDER BY id1 DESC;
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 > 'xyy' AND id2 < 'xxyyy' ORDER BY id1 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND (id2 <= 'xyy' OR id2 >= 'xxyyy');
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND (id2 <= 'xyy' OR id2 >= 'xxyyy');
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND (id2 <= 'xyy' OR id2 >= 'xxyyy') ORDER BY id1 DESC;
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND (id2 <= 'xyy' OR id2 >= 'xxyyy') ORDER BY id1 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND (id2 < 'xyy' OR id2 >= 'xxyyy');
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND (id2 < 'xyy' OR id2 >= 'xxyyy');
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND (id2 < 'xyy' OR id2 >= 'xxyyy') ORDER BY id1 DESC;
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND (id2 < 'xyy' OR id2 >= 'xxyyy') ORDER BY id1 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND (id2 <= 'xyy' OR id2 > 'xxyyy');
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND (id2 <= 'xyy' OR id2 > 'xxyyy');
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND (id2 <= 'xyy' OR id2 > 'xxyyy') ORDER BY id1 DESC;
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND (id2 <= 'xyy' OR id2 > 'xxyyy') ORDER BY id1 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND (id2 < 'xyy' OR id2 > 'xxyyy');
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND (id2 < 'xyy' OR id2 > 'xxyyy');
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND (id2 < 'xyy' OR id2 > 'xxyyy') ORDER BY id1 DESC;
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND (id2 < 'xyy' OR id2 > 'xxyyy') ORDER BY id1 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND (id2 < 'xyy' AND id2 > 'xxyyy');
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND (id2 < 'xyy' AND id2 > 'xxyyy');
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND (id2 < 'xyy' AND id2 > 'xxyyy') ORDER BY id1 DESC;
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND (id2 < 'xyy' AND id2 > 'xxyyy') ORDER BY id1 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 IN ('xyy', 'xxyyy');
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 IN ('xyy', 'xxyyy');
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 IN ('xyy', 'xxyyy') ORDER BY id1 DESC;
SELECT id1, id2 FROM o_pk3 WHERE id1 = 2 AND id2 IN ('xyy', 'xxyyy') ORDER BY id1 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 IN (2, 4) AND id2 IN ('xyy', 'xxyyy');
SELECT id1, id2 FROM o_pk3 WHERE id1 IN (2, 4) AND id2 IN ('xyy', 'xxyyy');
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 IN (2, 4) AND id2 IN ('xyy', 'xxyyy') ORDER BY id1 DESC;
SELECT id1, id2 FROM o_pk3 WHERE id1 IN (2, 4) AND id2 IN ('xyy', 'xxyyy') ORDER BY id1 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE (id1 = 2 AND id2 = 'xyy') OR (id1 = 4 AND id2 = 'x*y');
SELECT id1, id2 FROM o_pk3 WHERE (id1 = 2 AND id2 = 'xyy') OR (id1 = 4 AND id2 = 'x*y');
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE (id1 = 2 AND id2 = 'xyy') OR (id1 = 4 AND id2 = 'x*y') ORDER BY id1 DESC;
SELECT id1, id2 FROM o_pk3 WHERE (id1 = 2 AND id2 = 'xyy') OR (id1 = 4 AND id2 = 'x*y') ORDER BY id1 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 > 1 AND id2 < 'xxyyy';
SELECT id1, id2 FROM o_pk3 WHERE id1 > 1 AND id2 < 'xxyyy';
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 > 1 AND id2 < 'xxyyy' ORDER BY id1 DESC;
SELECT id1, id2 FROM o_pk3 WHERE id1 > 1 AND id2 < 'xxyyy' ORDER BY id1 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 > 1 AND id2 > 'xxyyy';
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 > 1 AND (id2 < 'xyy' OR id2 >= 'xxyyy');
SELECT id1, id2 FROM o_pk3 WHERE id1 > 1 AND (id2 < 'xyy' OR id2 >= 'xxyyy');
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 > 1 AND (id2 < 'xyy' OR id2 >= 'xxyyy') ORDER BY id1 DESC;
SELECT id1, id2 FROM o_pk3 WHERE id1 > 1 AND (id2 < 'xyy' OR id2 >= 'xxyyy') ORDER BY id1 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 > 1 AND id2 > 'xxyyy';
SELECT id1, id2 FROM o_pk3 WHERE id1 > 1 AND id2 > 'xxyyy';
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 > 1 AND id2 > 'xxyyy' ORDER BY id1 DESC;
SELECT id1, id2 FROM o_pk3 WHERE id1 > 1 AND id2 > 'xxyyy' ORDER BY id1 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 > 1 AND (id2 > 'xxyyy' OR id2 <'xyy');
SELECT id1, id2 FROM o_pk3 WHERE id1 > 1 AND (id2 > 'xxyyy' OR id2 <'xyy');
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 > 1 AND (id2 > 'xxyyy' OR id2 <'xyy') ORDER BY id1 DESC;
SELECT id1, id2 FROM o_pk3 WHERE id1 > 1 AND (id2 > 'xxyyy' OR id2 <'xyy') ORDER BY id1 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 > 1 AND id2 = 'xxyyy';
SELECT id1, id2 FROM o_pk3 WHERE id1 > 1 AND id2 = 'xxyyy';
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 > 1 AND id2 = 'xxyyy' ORDER BY id1 DESC;
SELECT id1, id2 FROM o_pk3 WHERE id1 > 1 AND id2 = 'xxyyy' ORDER BY id1 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 < 3 AND id2 < 'xxyyy';
SELECT id1, id2 FROM o_pk3 WHERE id1 < 3 AND id2 < 'xxyyy';
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 < 3 AND id2 < 'xxyyy' ORDER BY id1 DESC;
SELECT id1, id2 FROM o_pk3 WHERE id1 < 3 AND id2 < 'xxyyy' ORDER BY id1 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 < 3 AND id2 > 'xxyyy';
SELECT id1, id2 FROM o_pk3 WHERE id1 < 3 AND id2 > 'xxyyy';
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 < 3 AND id2 > 'xxyyy' ORDER BY id1 DESC;
SELECT id1, id2 FROM o_pk3 WHERE id1 < 3 AND id2 > 'xxyyy' ORDER BY id1 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 < 3 AND id2 = 'xxyyy';
SELECT id1, id2 FROM o_pk3 WHERE id1 < 3 AND id2 = 'xxyyy';
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 < 3 AND id2 = 'xxyyy' ORDER BY id1 DESC;
SELECT id1, id2 FROM o_pk3 WHERE id1 < 3 AND id2 = 'xxyyy' ORDER BY id1 DESC;
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 > 1 AND id2 IN ('xyy', 'xxyyy');
SELECT id1, id2 FROM o_pk3 WHERE id1 > 1 AND id2 IN ('xyy', 'xxyyy');
EXPLAIN (COSTS off) SELECT id1, id2 FROM o_pk3 WHERE id1 > 1 AND id2 IN ('xyy', 'xxyyy') ORDER BY id1 DESC;
SELECT id1, id2 FROM o_pk3 WHERE id1 > 1 AND id2 IN ('xyy', 'xxyyy') ORDER BY id1 DESC;
