name: dockerTEST

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test-docker-builds:
    strategy:
      fail-fast: true
      matrix:
        postgres: [16, 15]
        compiler: [clang]
        distr:  [alpine, ubuntu]
        include:
          - distr-version: 3.19
            distr: alpine
          - distr-version: focal
            distr: ubuntu

    name: docker ${{ matrix.postgres }}-${{ matrix.compiler }}-${{ matrix.distr }}-${{ matrix.distr-version }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.alpine == 'edge' }}

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: docker build orioletest:${{ matrix.postgres }}-${{ matrix.compiler }}-${{ matrix.distr }}-${{ matrix.distr-version }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.distr == 'ubuntu' && 'Dockerfile.ubuntu' || 'Dockerfile' }}
          platforms: linux/amd64
          push: false
          pull: true
          tags: orioletest:${{ matrix.postgres }}-${{ matrix.compiler }}-${{ matrix.distr }}-${{ matrix.distr-version }}
          build-args: |
            ALPINE_VERSION=${{ matrix.distr == 'alpine' && matrix.distr-version || '' }}
            UBUNTU_VERSION=${{ matrix.distr == 'ubuntu' && matrix.distr-version || '' }}
            PG_MAJOR=${{ matrix.postgres }}
            BUILD_CC_COMPILER=${{ matrix.compiler }}
            DOCKER_PG_LLVM_DEPS=llvm-dev clang
