name: dockerTEST

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test-docker-builds:
    strategy:
      fail-fast: true
      matrix:
        postgres: [16, 13]
        compiler: [clang, gcc]
        alpine:  [edge, 3.18, 3.13]

    name: docker ${{ matrix.postgres }}-${{ matrix.compiler }}-alpine${{ matrix.alpine }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.alpine == 'edge' }}

    steps:
      - name: Set DOCKER_PG_LLVM_DEPS
        run: |
          if [[ "${{ matrix.alpine }}" == "3.18" ]] || [[ "${{ matrix.alpine }}" == "edge" ]]; \
          then echo "DOCKER_PG_LLVM_DEPS=llvm15-dev clang15" >> $GITHUB_ENV; \
          else echo "DOCKER_PG_LLVM_DEPS=llvm-dev clang"     >> $GITHUB_ENV; \
          fi

      - name: Echo DOCKER_PG_LLVM_DEP
        run: echo "DOCKER_PG_LLVM_DEP = ${{ env.DOCKER_PG_LLVM_DEPS }} "

      - name: Checkout source
        uses: actions/checkout@v3

      - name: docker build orioletest:${{ matrix.postgres }}-${{ matrix.compiler }}-alpine${{ matrix.alpine }}
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: false
          pull: true
          tags: orioletest:${{ matrix.postgres }}-${{ matrix.compiler }}-alpine${{ matrix.alpine }}
          build-args: |
            ALPINE_VERSION=${{ matrix.alpine }}
            BUILD_CC_COMPILER=${{ matrix.compiler }}
            PG_MAJOR=${{ matrix.postgres }}
            DOCKER_PG_LLVM_DEPS=${{ env.DOCKER_PG_LLVM_DEPS }}
